/**
 * 🥯 i18n-bakery - Translation File Manager (Use Case Layer)
 * 
 * Orchestrates the auto-creation and maintenance of translation files.
 * This is the main service for Phase 9 functionality.
 * 
 * @module use-cases/TranslationFileManager
 */

import { KeyParser, ParsedKey } from '../domain/KeyParser';
import { PathResolver } from '../domain/KeyParser';
import { VariableDetector, VariableSignature } from '../domain/VariableDetection';
import {
  FileWriter,
  TranslationFileContent,
  TranslationEntryContent,
  VariantContent,
} from '../domain/FileWriter';
import { Locale, Namespace, Key } from '../domain/types';

/**
 * Configuration for the TranslationFileManager.
 */
export interface TranslationFileManagerConfig {
  /**
   * Key parser for parsing translation keys
   */
  keyParser: KeyParser;
  
  /**
   * Path resolver for resolving file paths
   */
  pathResolver: PathResolver;
  
  /**
   * Variable detector for detecting variables in translations
   */
  variableDetector: VariableDetector;
  
  /**
   * File writer for writing translation files
   */
  fileWriter: FileWriter;
  
  /**
   * Merge mode for updating existing files
   * @default 'append'
   */
  mergeMode?: 'append' | 'replace';
  
  /**
   * Whether to enable debug logging
   * @default false
   */
  debug?: boolean;
}

/**
 * Service for managing translation files.
 * 
 * This service orchestrates the auto-creation and maintenance of translation files
 * using the components from Phases 7 and 8.
 */
export class TranslationFileManager {
  private keyParser: KeyParser;
  private pathResolver: PathResolver;
  private variableDetector: VariableDetector;
  private fileWriter: FileWriter;
  private mergeMode: 'append' | 'replace';
  private debug: boolean;

  constructor(config: TranslationFileManagerConfig) {
    this.keyParser = config.keyParser;
    this.pathResolver = config.pathResolver;
    this.variableDetector = config.variableDetector;
    this.fileWriter = config.fileWriter;
    this.mergeMode = config.mergeMode || 'append';
    this.debug = config.debug || false;
  }

  /**
   * Creates or updates a translation entry.
   * 
   * This is the main method for Phase 9.1 - Auto-creation of entries.
   * 
   * @param locale - The locale (e.g., "en", "es-MX")
   * @param key - The translation key (e.g., "orders:meal.title")
   * @param value - The translation value (e.g., "{{meal}} - ${{price}}")
   * @param vars - Variables used in the translation
   * @param autoGenerated - Whether this entry was auto-generated
   */
  async createOrUpdateEntry(
    locale: Locale,
    key: Key,
    value: string,
    vars?: Record<string, any>,
    autoGenerated: boolean = true
  ): Promise<void> {
    // Step 1: Parse the key using KeyParser
    const parsedKey = this.keyParser.parse(key);
    
    if (this.debug) {
      console.log(`[TranslationFileManager] Parsed key:`, parsedKey);
    }

    // Step 2: Detect variables and create signature
    const signature = this.variableDetector.detectVariables(vars);
    const signatureKey = this.variableDetector.createSignatureKey(signature);
    
    if (this.debug) {
      console.log(`[TranslationFileManager] Variable signature:`, signature, '→', signatureKey);
    }

    // Step 3: Resolve file path using PathResolver
    const filePath = this.pathResolver.resolve(locale, parsedKey);
    
    if (this.debug) {
      console.log(`[TranslationFileManager] File path:`, filePath);
    }

    // Step 4: Create translation content
    const propertyKey = this.getPropertyKey(parsedKey);
    const content = this.createTranslationContent(
      propertyKey,
      signatureKey,
      value,
      signature,
      autoGenerated
    );

    // Step 5: Write or merge the file
    await this.fileWriter.merge(filePath, content, this.mergeMode);
    
    if (this.debug) {
      console.log(`[TranslationFileManager] Successfully wrote to ${filePath}`);
    }
  }

  /**
   * Creates a translation entry with auto-generated placeholder value.
   * 
   * @param locale - The locale
   * @param key - The translation key
   * @param vars - Variables used in the translation
   */
  async createEntryWithPlaceholder(
    locale: Locale,
    key: Key,
    vars?: Record<string, any>
  ): Promise<void> {
    const signature = this.variableDetector.detectVariables(vars);
    const placeholderValue = this.variableDetector.generateDefaultValue(signature);
    
    await this.createOrUpdateEntry(locale, key, placeholderValue, vars, true);
  }

  /**
   * Checks if an entry exists for a specific key and variable signature.
   * 
   * @param locale - The locale
   * @param key - The translation key
   * @param vars - Variables to check
   * @returns Promise that resolves with true if entry exists
   */
  async entryExists(
    locale: Locale,
    key: Key,
    vars?: Record<string, any>
  ): Promise<boolean> {
    const parsedKey = this.keyParser.parse(key);
    const filePath = this.pathResolver.resolve(locale, parsedKey);
    
    if (!(await this.fileWriter.exists(filePath))) {
      return false;
    }

    const content = await this.fileWriter.read(filePath);
    if (!content) {
      return false;
    }

    const propertyKey = this.getPropertyKey(parsedKey);
    const signature = this.variableDetector.detectVariables(vars);
    const signatureKey = this.variableDetector.createSignatureKey(signature);

    return !!(content[propertyKey]?.variants[signatureKey]);
  }

  /**
   * Gets the property key from a parsed key.
   * This is the key used in the JSON file.
   * 
   * @param parsedKey - The parsed key
   * @returns Property key
   */
  private getPropertyKey(parsedKey: ParsedKey): string {
    return parsedKey.propertyPath.join('.');
  }

  /**
   * Creates translation content structure.
   * 
   * @param propertyKey - The property key
   * @param signatureKey - The signature key
   * @param value - The translation value
   * @param signature - The variable signature
   * @param autoGenerated - Whether this is auto-generated
   * @returns Translation content
   */
  private createTranslationContent(
    propertyKey: string,
    signatureKey: string,
    value: string,
    signature: VariableSignature,
    autoGenerated: boolean
  ): TranslationFileContent {
    const variant: VariantContent = {
      value,
      variables: signature,
      autoGenerated,
      timestamp: Date.now(),
    };

    const entry: TranslationEntryContent = {
      variants: {
        [signatureKey]: variant,
      },
    };

    return {
      [propertyKey]: entry,
    };
  }
}
