/**
 * 🥯 i18n-bakery - Translation File Manager Tests
 * 
 * Comprehensive tests for the TranslationFileManager use case.
 * Tests the auto-creation and maintenance of translation files.
 */

import { describe, it, expect, beforeEach, vi } from 'vitest';
import { TranslationFileManager } from '../src/use-cases/TranslationFileManager';
import { DefaultKeyParser } from '../src/adapters/DefaultKeyParser';
import { FileSystemPathResolver } from '../src/adapters/FileSystemPathResolver';
import { DefaultVariableDetector } from '../src/adapters/DefaultVariableDetector';
import type { FileWriter, TranslationFileContent } from '../src/domain/FileWriter';

describe('TranslationFileManager', () => {
  let manager: TranslationFileManager;
  let mockFileWriter: FileWriter;
  let writtenFiles: Map<string, TranslationFileContent>;

  beforeEach(() => {
    // Reset written files
    writtenFiles = new Map();

    // Create mock FileWriter
    mockFileWriter = {
      write: vi.fn(async (filePath: string, content: TranslationFileContent) => {
        writtenFiles.set(filePath, content);
      }),
      read: vi.fn(async (filePath: string) => {
        return writtenFiles.get(filePath) || null;
      }),
      exists: vi.fn(async (filePath: string) => {
        return writtenFiles.has(filePath);
      }),
      merge: vi.fn(async (filePath: string, newContent: TranslationFileContent, mode: 'append' | 'replace') => {
        const existing = writtenFiles.get(filePath);
        if (!existing) {
          writtenFiles.set(filePath, newContent);
          return;
        }

        // Simple merge logic for testing
        const merged = { ...existing };
        for (const [key, entry] of Object.entries(newContent)) {
          if (!merged[key]) {
            merged[key] = entry;
          } else {
            for (const [sigKey, variant] of Object.entries(entry.variants)) {
              if (mode === 'append' && merged[key].variants[sigKey]) {
                continue;
              }
              merged[key].variants[sigKey] = variant;
            }
          }
        }
        writtenFiles.set(filePath, merged);
      }),
    };

    // Create manager with real adapters and mock file writer
    manager = new TranslationFileManager({
      keyParser: new DefaultKeyParser(),
      pathResolver: new FileSystemPathResolver({ baseDir: './locales' }),
      variableDetector: new DefaultVariableDetector(),
      fileWriter: mockFileWriter,
      mergeMode: 'append',
      debug: false,
    });
  });

  describe('createOrUpdateEntry', () => {
    it('should create a new entry with variables', async () => {
      await manager.createOrUpdateEntry(
        'en',
        'orders:meal.title',
        '{{meal}} - ${{price}}',
        { meal: 'Pizza', price: 120 },
        true
      );

      expect(mockFileWriter.merge).toHaveBeenCalled();
      
      const content = writtenFiles.get('./locales/en/orders/meal.json');
      expect(content).toBeDefined();
      expect(content!['title']).toBeDefined();
      expect(content!['title'].variants['meal_price']).toBeDefined();
      expect(content!['title'].variants['meal_price'].value).toBe('{{meal}} - ${{price}}');
      expect(content!['title'].variants['meal_price'].variables).toEqual(['meal', 'price']);
      expect(content!['title'].variants['meal_price'].autoGenerated).toBe(true);
    });

    it('should create entry for global file when no colon', async () => {
      await manager.createOrUpdateEntry(
        'en',
        'user.profile.name',
        '{{name}}',
        { name: 'John' },
        true
      );

      const content = writtenFiles.get('./locales/en/global.json');
      expect(content).toBeDefined();
      expect(content!['user.profile.name']).toBeDefined();
    });

    it('should handle nested properties', async () => {
      await manager.createOrUpdateEntry(
        'en',
        'orders:meal.user.profile.name',
        '{{name}}',
        { name: 'Emma' },
        true
      );

      const content = writtenFiles.get('./locales/en/orders/meal.json');
      expect(content).toBeDefined();
      expect(content!['user.profile.name']).toBeDefined();
    });

    it('should create multiple variants for same key', async () => {
      // First variant: only meal
      await manager.createOrUpdateEntry(
        'en',
        'orders:meal.title',
        '{{meal}}',
        { meal: 'Pizza' },
        true
      );

      // Second variant: meal and price
      await manager.createOrUpdateEntry(
        'en',
        'orders:meal.title',
        '{{meal}} - ${{price}}',
        { meal: 'Pizza', price: 120 },
        true
      );

      const content = writtenFiles.get('./locales/en/orders/meal.json');
      expect(content).toBeDefined();
      expect(Object.keys(content!['title'].variants)).toHaveLength(2);
      expect(content!['title'].variants['meal']).toBeDefined();
      expect(content!['title'].variants['meal_price']).toBeDefined();
    });

    it('should respect append mode and not overwrite existing variants', async () => {
      // Create initial entry
      await manager.createOrUpdateEntry(
        'en',
        'orders:meal.title',
        'Original value',
        { meal: 'Pizza' },
        false
      );

      // Try to update with append mode
      await manager.createOrUpdateEntry(
        'en',
        'orders:meal.title',
        'New value',
        { meal: 'Tacos' },
        true
      );

      const content = writtenFiles.get('./locales/en/orders/meal.json');
      expect(content!['title'].variants['meal'].value).toBe('Original value');
      expect(content!['title'].variants['meal'].autoGenerated).toBe(false);
    });
  });

  describe('createEntryWithPlaceholder', () => {
    it('should create entry with auto-generated placeholder', async () => {
      await manager.createEntryWithPlaceholder(
        'en',
        'orders:meal.title',
        { meal: 'Pizza', price: 120 }
      );

      const content = writtenFiles.get('./locales/en/orders/meal.json');
      expect(content).toBeDefined();
      expect(content!['title'].variants['meal_price'].value).toBe('{{meal}} {{price}}');
      expect(content!['title'].variants['meal_price'].autoGenerated).toBe(true);
    });

    it('should handle entry without variables', async () => {
      await manager.createEntryWithPlaceholder(
        'en',
        'auth:login.button'
      );

      const content = writtenFiles.get('./locales/en/auth/login.json');
      expect(content).toBeDefined();
      expect(content!['button'].variants['default']).toBeDefined();
      expect(content!['button'].variants['default'].value).toBe('');
    });
  });

  describe('entryExists', () => {
    it('should return true when entry exists', async () => {
      await manager.createOrUpdateEntry(
        'en',
        'orders:meal.title',
        '{{meal}}',
        { meal: 'Pizza' },
        true
      );

      const exists = await manager.entryExists('en', 'orders:meal.title', { meal: 'Pizza' });
      expect(exists).toBe(true);
    });

    it('should return false when entry does not exist', async () => {
      const exists = await manager.entryExists('en', 'orders:meal.title', { meal: 'Pizza' });
      expect(exists).toBe(false);
    });

    it('should return false when file exists but variant does not', async () => {
      await manager.createOrUpdateEntry(
        'en',
        'orders:meal.title',
        '{{meal}}',
        { meal: 'Pizza' },
        true
      );

      const exists = await manager.entryExists('en', 'orders:meal.title', { meal: 'Pizza', price: 120 });
      expect(exists).toBe(false);
    });
  });

  describe('integration scenarios', () => {
    it('should handle complex multi-locale scenario', async () => {
      // English
      await manager.createOrUpdateEntry('en', 'orders:meal.title', 'Meal: {{meal}}', { meal: 'Pizza' });
      
      // Spanish
      await manager.createOrUpdateEntry('es', 'orders:meal.title', 'Comida: {{meal}}', { meal: 'Pizza' });
      
      // French
      await manager.createOrUpdateEntry('fr', 'orders:meal.title', 'Repas: {{meal}}', { meal: 'Pizza' });

      expect(writtenFiles.size).toBe(3);
      expect(writtenFiles.has('./locales/en/orders/meal.json')).toBe(true);
      expect(writtenFiles.has('./locales/es/orders/meal.json')).toBe(true);
      expect(writtenFiles.has('./locales/fr/orders/meal.json')).toBe(true);
    });

    it('should handle hierarchical directory structure', async () => {
      await manager.createOrUpdateEntry(
        'en',
        'app:features:orders:meal.component.title',
        '{{meal}}',
        { meal: 'Pizza' }
      );

      const content = writtenFiles.get('./locales/en/app/features/orders/meal/component.json');
      expect(content).toBeDefined();
      expect(content!['title']).toBeDefined();
    });
  });
});
