/**
 * 🥯 i18n-bakery - Variable Detection (Domain Layer)
 * 
 * This file defines the domain interfaces for detecting and managing
 * variables in translation keys, implementing the Variable Signature System
 * from Phase 8 of the workplan.
 * 
 * @module domain/VariableDetection
 */

/**
 * Represents a variable signature - a unique identifier for a set of variables.
 * 
 * The signature is a sorted array of variable names, used to differentiate
 * between different variants of the same translation key.
 * 
 * @example
 * Variables: { meal: "Pizza", price: 120 }
 * Signature: ["meal", "price"]
 */
export type VariableSignature = string[];

/**
 * Represents a translation entry with variable information.
 */
export interface TranslationEntry {
  /**
   * The actual translation text with variable placeholders
   * @example "{{meal}} costs ${{price}}"
   */
  value: string;
  
  /**
   * List of variable names used in this translation
   */
  variables: string[];
  
  /**
   * Whether this entry was auto-generated
   */
  autoGenerated?: boolean;
  
  /**
   * Timestamp of when this entry was created/updated
   */
  timestamp?: number;
}

/**
 * Represents a translation key with multiple variants based on variable signatures.
 * 
 * This structure allows the same key to have different translations
 * depending on which variables are provided.
 * 
 * @example
 * {
 *   "title": {
 *     "variants": {
 *       "meal": {
 *         "value": "{{meal}}",
 *         "variables": ["meal"]
 *       },
 *       "meal_price": {
 *         "value": "{{meal}} - ${{price}}",
 *         "variables": ["meal", "price"]
 *       }
 *     }
 *   }
 * }
 */
export interface TranslationVariants {
  /**
   * Map of signature keys to translation entries
   * Key format: variable names joined by underscore (e.g., "meal_price")
   */
  variants: Record<string, TranslationEntry>;
}

/**
 * Configuration for variable detection.
 */
export interface VariableDetectorConfig {
  /**
   * Whether to auto-generate missing translation entries
   * @default true
   */
  autoGenerate?: boolean;
  
  /**
   * Whether to create variants for different variable signatures
   * @default true
   */
  enableVariants?: boolean;
  
  /**
   * Default template for auto-generated translations
   * @default "{{var1}} {{var2}} ..."
   */
  defaultTemplate?: 'variables-only' | 'empty';
}

/**
 * Port (Interface) for detecting variables in translation calls.
 * 
 * This interface abstracts the variable detection strategy,
 * following the Dependency Inversion Principle (SOLID).
 */
export interface VariableDetector {
  /**
   * Detects variables from a variables object and creates a signature.
   * 
   * @param vars - The variables object passed to t()
   * @returns Sorted array of variable names (signature)
   * 
   * @example
   * detectVariables({ meal: "Pizza", price: 120 })
   * // ["meal", "price"]
   */
  detectVariables(vars?: Record<string, any>): VariableSignature;
  
  /**
   * Creates a signature key from a variable signature.
   * This key is used to identify variants in storage.
   * 
   * @param signature - The variable signature
   * @returns String key (e.g., "meal_price")
   * 
   * @example
   * createSignatureKey(["meal", "price"])
   * // "meal_price"
   */
  createSignatureKey(signature: VariableSignature): string;
  
  /**
   * Generates a default translation value based on variables.
   * 
   * @param signature - The variable signature
   * @param template - Template style to use
   * @returns Generated translation value
   * 
   * @example
   * generateDefaultValue(["meal", "price"], "variables-only")
   * // "{{meal}} {{price}}"
   */
  generateDefaultValue(signature: VariableSignature, template?: 'variables-only' | 'empty'): string;
}

/**
 * Port (Interface) for managing translation entries with variable support.
 * 
 * This interface handles the creation and retrieval of translation entries
 * with support for multiple variants based on variable signatures.
 */
export interface TranslationEntryManager {
  /**
   * Gets a translation entry for a specific key and variable signature.
   * 
   * @param locale - The locale
   * @param namespace - The namespace
   * @param key - The translation key
   * @param signature - The variable signature
   * @returns The translation entry, or null if not found
   */
  getEntry(
    locale: string,
    namespace: string,
    key: string,
    signature: VariableSignature
  ): TranslationEntry | null;
  
  /**
   * Creates or updates a translation entry.
   * 
   * @param locale - The locale
   * @param namespace - The namespace
   * @param key - The translation key
   * @param signature - The variable signature
   * @param value - The translation value
   * @param autoGenerated - Whether this is auto-generated
   */
  setEntry(
    locale: string,
    namespace: string,
    key: string,
    signature: VariableSignature,
    value: string,
    autoGenerated?: boolean
  ): void;
  
  /**
   * Checks if an entry exists for a specific key and signature.
   * 
   * @param locale - The locale
   * @param namespace - The namespace
   * @param key - The translation key
   * @param signature - The variable signature
   * @returns True if entry exists
   */
  hasEntry(
    locale: string,
    namespace: string,
    key: string,
    signature: VariableSignature
  ): boolean;
  
  /**
   * Gets all variants for a specific key.
   * 
   * @param locale - The locale
   * @param namespace - The namespace
   * @param key - The translation key
   * @returns All variants, or null if key doesn't exist
   */
  getAllVariants(
    locale: string,
    namespace: string,
    key: string
  ): TranslationVariants | null;
}
