/**
 * 🥯 i18n-bakery - File Writer (Domain Layer)
 * 
 * This file defines the domain interfaces for writing translation files
 * in different formats following Clean Architecture principles.
 * 
 * @module domain/FileWriter
 */

import { OutputFormat } from './types';

/**
 * Represents the content structure for a translation file.
 * This is format-agnostic and will be serialized by the FileWriter.
 */
export interface TranslationFileContent {
  /**
   * The translation entries organized by key
   */
  [key: string]: TranslationEntryContent;
}

/**
 * Content for a single translation entry with its variants.
 */
export interface TranslationEntryContent {
  /**
   * Different variants of this translation based on variable signatures
   */
  variants: {
    [signatureKey: string]: VariantContent;
  };
}

/**
 * Content for a single variant.
 */
export interface VariantContent {
  /**
   * The translation value with placeholders
   */
  value: string;
  
  /**
   * List of variables used in this variant
   */
  variables: string[];
  
  /**
   * Whether this entry was auto-generated
   */
  autoGenerated?: boolean;
  
  /**
   * Timestamp of creation/update
   */
  timestamp?: number;
}

/**
 * Configuration for file writing operations.
 */
export interface FileWriterConfig {
  /**
   * Output format for the file
   */
  format: OutputFormat;
  
  /**
   * Whether to format the output (pretty-print)
   * @default true
   */
  prettyPrint?: boolean;
  
  /**
   * Indentation size for pretty-printing
   * @default 2
   */
  indentSize?: number;
  
  /**
   * Whether to create directories if they don't exist
   * @default true
   */
  createDirectories?: boolean;
}

/**
 * Port (Interface) for writing translation files.
 * 
 * Following the Dependency Inversion Principle (SOLID),
 * this interface allows different file writing strategies
 * to be implemented without changing the domain logic.
 */
export interface FileWriter {
  /**
   * Writes translation content to a file.
   * 
   * @param filePath - Absolute path to the file
   * @param content - Translation content to write
   * @returns Promise that resolves when writing is complete
   * 
   * @example
   * await writer.write('./locales/en/orders/meal.json', {
   *   title: {
   *     variants: {
   *       meal: { value: '{{meal}}', variables: ['meal'] }
   *     }
   *   }
   * });
   */
  write(filePath: string, content: TranslationFileContent): Promise<void>;
  
  /**
   * Reads translation content from a file.
   * 
   * @param filePath - Absolute path to the file
   * @returns Promise that resolves with the file content, or null if file doesn't exist
   * 
   * @example
   * const content = await writer.read('./locales/en/orders/meal.json');
   */
  read(filePath: string): Promise<TranslationFileContent | null>;
  
  /**
   * Checks if a file exists.
   * 
   * @param filePath - Absolute path to the file
   * @returns Promise that resolves with true if file exists
   */
  exists(filePath: string): Promise<boolean>;
  
  /**
   * Merges new content with existing file content.
   * This is useful for append-only mode.
   * 
   * @param filePath - Absolute path to the file
   * @param newContent - New content to merge
   * @param mode - Merge mode: 'append' (don't overwrite) or 'replace' (overwrite)
   * @returns Promise that resolves when merging is complete
   */
  merge(
    filePath: string,
    newContent: TranslationFileContent,
    mode: 'append' | 'replace'
  ): Promise<void>;
}

/**
 * Port (Interface) for managing file system operations.
 * 
 * This abstraction allows different storage backends
 * (local filesystem, S3, etc.) to be used.
 */
export interface FileSystemManager {
  /**
   * Creates a directory and all parent directories if they don't exist.
   * 
   * @param dirPath - Absolute path to the directory
   * @returns Promise that resolves when directory is created
   */
  createDirectory(dirPath: string): Promise<void>;
  
  /**
   * Checks if a directory exists.
   * 
   * @param dirPath - Absolute path to the directory
   * @returns Promise that resolves with true if directory exists
   */
  directoryExists(dirPath: string): Promise<boolean>;
  
  /**
   * Gets the directory path from a file path.
   * 
   * @param filePath - Absolute path to the file
   * @returns Directory path
   */
  getDirectoryPath(filePath: string): string;
}
